config/routes.rb
Kami::Application.routes.draw do
  resources :media do 
    resources :stories
  end

  resources :blogs do 
    resources :entries
  end

  root :to => "media#index"

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :medium
  scope :entries, where(:launch => true)
  scope :unlaunches, where(:launch => false)
  scope :newer, order("created_at desc")
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  before_filter :find_medium
  
  # GET /stories
  # GET /stories.xml
  def index
    @stories = @medium.stories.newer.entries.page params[:page]
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.xml
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.xml
  def new
    @story = @medium.stories.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.xml
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to(medium_story_path(@story.medium, @story), :notice => 'Story was successfully created.') }
        format.xml  { render :xml => @story, :status => :created, :location => @story }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.xml
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to(@story, :notice => 'Story was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.xml
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to(stories_url) }
      format.xml  { head :ok }
    end
  end

  private 

    def find_medium 
      @medium = Medium.find params[:medium_id]
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.haml
= form_for @story, :url => "#{@story.new_record? ? medium_stories_path(@medium) : medium_story_path(@medium, @story)}" do |f|
  -if @story.errors.any?
    #error_explanation
      %h2= "#{pluralize(@story.errors.count, "error")} prohibited this story from being saved:"
      %ul
        - @story.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :medium_id
    = f.hidden_field :medium_id
    = @story.medium.name
  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/stories/edit.html.haml
%h1 Editing story

= render 'form'

= link_to 'Show', @story
\|
= link_to 'Back', stories_path

app/views/stories/index.html.haml
%h1 Listing stories

= paginate @stories

%table
  %tr
    %th Medium
    %th Title
    %th
    %th
    %th

  - @stories.each do |story|
    %tr
      %td= story.medium_id
      %td= story.title
      %td= link_to 'Show', medium_story_path(@medium, story)
      %td= link_to 'Edit', edit_medium_story_path(@medium, story)
      %td= link_to 'Destroy', medium_story_path(@medium, story), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Story', new_medium_story_path(@medium.id)

app/views/stories/new.html.haml
%h1 New story

= render 'form'

= link_to 'Back', medium_stories_path(@medium)

app/views/stories/show.html.haml
%p#notice= notice

%p
  %b Medium:
  = @story.medium_id
%p
  %b Title:
  = @story.title

= link_to 'Edit', edit_medium_story_path(@medium, @story)
\|
= link_to 'Back', medium_stories_path(@medium)