config/routes.rb
Kami::Application.routes.draw do
  resources :media do 
    resources :stories
  end

  resources :blogs do 
    resources :entries
  end

  root :to => "media#index"

end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  # GET /media
  # GET /media.xml
  def index
    @media = Medium.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @media }
    end
  end

  # GET /media/1
  # GET /media/1.xml
  def show
    @medium = Medium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @medium }
    end
  end

  # GET /media/new
  # GET /media/new.xml
  def new
    @medium = Medium.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @medium }
    end
  end

  # GET /media/1/edit
  def edit
    @medium = Medium.find(params[:id])
  end

  # POST /media
  # POST /media.xml
  def create
    @medium = Medium.new(params[:medium])

    respond_to do |format|
      if @medium.save
        format.html { redirect_to(@medium, :notice => 'Medium was successfully created.') }
        format.xml  { render :xml => @medium, :status => :created, :location => @medium }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @medium.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /media/1
  # PUT /media/1.xml
  def update
    @medium = Medium.find(params[:id])

    respond_to do |format|
      if @medium.update_attributes(params[:medium])
        format.html { redirect_to(@medium, :notice => 'Medium was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @medium.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.xml
  def destroy
    @medium = Medium.find(params[:id])
    @medium.destroy

    respond_to do |format|
      format.html { redirect_to(media_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/media_helper.rb
module MediaHelper
end

app/views/media/_form.html.haml
= form_for @medium do |f|
  -if @medium.errors.any?
    #error_explanation
      %h2= "#{pluralize(@medium.errors.count, "error")} prohibited this medium from being saved:"
      %ul
        - @medium.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/media/edit.html.haml
%h1 Editing medium

= render 'form'

= link_to 'Show', @medium
\|
= link_to 'Back', media_path

app/views/media/index.html.haml
%h1 Listing media

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @media.each do |medium|
    %tr
      %td= medium.name
      %td= link_to 'Show', medium
      %td= link_to 'Edit', edit_medium_path(medium)
      %td= link_to 'Destroy', medium, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Medium', new_medium_path

app/views/media/new.html.haml
%h1 New medium

= render 'form'

= link_to 'Back', media_path

app/views/media/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @medium.name

  = link_to "belongs_to stories", medium_stories_path(@medium)

= link_to 'Edit', edit_medium_path(@medium)
\|
= link_to 'Back', media_path